name: Deploy via ftp
on: push
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir:
            description: "Local directory"
            required: false
            default: "."
          options:
            description: "Additional mirror command options"
            required: false
            default: ""
          runs:
            using: "docker"
            image: "Dockerfile"
          branding:
            color: "red"
            icon: "upload-cloud"
